name: smoke testing

on:
  workflow_dispatch:
    inputs:
      grid_url:
        required: true
        type: string
        description: Grid to run tests on (local by default)
        default: http://localhost:4444

      chrome_131_0:
        description: 'Chrome (131.0)'
        required: false
        type: boolean

      firefox_133_0:
        description: 'Firefox (133.0)'
        required: false
        type: boolean

jobs:
  TestChrome_131_0:
    name: Test Chrome 131.0
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.chrome_131_0 == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Launch standalone grid - Chrome
        if: ${{ contains(github.event.inputs.grid_url, 'localhost') }}
        run: |
          docker run --name grid_container -d -p 4444:4444 --shm-size=2gb selenium/standalone-chrome:131.0-chromedriver-131.0-grid-4.27.0-20250101

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Tests
        run: |
          export BROWSER=chrome
          export GRID_URL=${{ github.event.inputs.grid_url }}
          mvn -q clean test -DsuiteXmlFile=testng-suites/testng-smoke.xml

      - name: Generate Allure report
        run: mvn allure:report

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

      - name: Publish Allure Report to GitHub Pages (optional)
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin


      - name: Tear down Grid
        run: docker stop grid_container || true

  TestFirefox_133_0:
    name: Test Firefox 133.0
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.firefox_133_0 == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Launch standalone grid - Firefox
        if: ${{ contains(github.event.inputs.grid_url, 'localhost') }}
        run: |
          docker run --name grid_container -d -p 4444:4444 --shm-size=2gb selenium/standalone-firefox:133.0-geckodriver-0.35-grid-4.27.0-20250101

      - name: Run Tests
        run: |
          export BROWSER=firefox
          export GRID_URL=${{ github.event.inputs.grid_url }}
          mvn -q clean test -DsuiteXmlFile=testng-suites/testng-smoke.xml

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          tar -zxvf allure-2.24.0.tgz
          mv allure-2.24.0 allure
          chmod +x allure/bin/allure

      - name: Generate Allure HTML Report
        run: |
          ./allure/bin/allure generate target/allure-results -o allure-report-fx --clean

      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-firefox
          path: allure-report-fx

      - name: Tear down Grid
        run: docker stop grid_container || true
